### PR TITLE
Integration test for MIPS

### PR DESCRIPTION
**Pull request by eQu1NoX**

### CODE REVIEW

**Comment by eQu1NoX** [comment]
Works locally.

**Comment by zachriggle** [comment]
Can't be merged until it passes CI

**Comment by zachriggle** [comment]
Since we cannot use `sudo` to install anything, and since we're only running statically-linked binaries under user emulation (i.e. don't need `libc.so` for ARM), we just need to add `qemu-mips-static` (and the corresponding ones for other arches) to the set of files which Travis has access to.

We do something similar for Binutils for the foreign architectures (https://github.com/binjitsu/binjitsu/blob/master/.travis_install.sh#L22-L29).  I'll get the QEMU binaries up and running for you so that we can work on getting the tests to pass.

**Comment by eQu1NoX** [comment]
Sounds good !

**Comment by zachriggle** [comment]
Changes are complete.  Rebase your changes on top of master and `push -f` :smile:

**Pull request closed without merging**
