### PR TITLE
Integration test for Aarch64 working

### PR DESCRIPTION
**Pull request by eQu1NoX**

### CODE REVIEW

**Comment by eQu1NoX** [comment]
"Exception: Could not find 'as' installed for ContextType(arch = 'aarch64', bits = 64, endian = 'little')"

Additionally, is there a way to specify qemu-aarch-static version as >= 2.3.92?

**Comment by zachriggle** [comment]
I've added `aarch64` binutils, so the assembler should work now.  However, I'd like to stick to versions of QEMU which Ubuntu currently ships (which is 2.0.0).

If it's *not possible* to get the tests to run successfully on 2.0.0, we can add an exception for the test (e.g. add `# doctest: +SKIP` to each line).

**Comment by zachriggle** [comment]
Actually, I just ran the tests with QEMU 2.3 instead of QEMU 2.1, and all of the tests appear to work.

Rebase your changes on top of it and we can test it :)

**Comment by eQu1NoX** [comment]
Hmm seems binutils isn't getting installed properly.
"""
--2015-07-29 12:44:10-- https://launchpad.net/~pwntools/+archive/ubuntu/binutils/+files/binutils-aarch64-linux-gnu_2.22-6ubuntu1.1cross0.11pwntools12~precise_amd64.deb
Resolving launchpad.net (launchpad.net)... 91.189.89.223, 91.189.89.222
Connecting to launchpad.net (launchpad.net)|91.189.89.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-29 12:44:11 ERROR 404: Not Found.
"""

**Comment by zachriggle** [comment]
Yep, looks like AArch64 wasn't added to Binutils until late 2012, whereas Ubuntu 12.04 was released in April 2012.  Given that we're using the statically-linked versions, we *should* be able to force them onto Travis, but I'm not sure how much work it'll be.

From *ChangeLog-2012*:

```
2012-08-13  Ian Bolton  <ian.bolton@arm.com>
            Laurent Desnogues  <laurent.desnogues@arm.com>
            Jim MacArthur  <jim.macarthur@arm.com>
            Marcus Shawcroft  <marcus.shawcroft@arm.com>
            Nigel Stephens  <nigel.stephens@arm.com>
            Ramana Radhakrishnan  <ramana.radhakrishnan@arm.com>
            Richard Earnshaw  <rearnsha@arm.com>
            Sofiane Naci  <sofiane.naci@arm.com>
            Tejas Belagod  <tejas.belagod@arm.com>
            Yufeng Zhang  <yufeng.zhang@arm.com>

	* Makefile.am: Add AArch64.
	* Makefile.in: Regenerate.
	* config/tc-aarch64.c: New file.
	* config/tc-aarch64.h: New file.
	* configure.tgt: Add AArch64.
	* doc/Makefile.am: Add AArch64.
	* doc/Makefile.in: Regenerate.
	* doc/all.texi: Add AArch64.
	* doc/as.texinfo: Add AArch64.
	* doc/c-aarch64.texi: New file.
	* po/POTFILES.in: Regenerate.
	* NEWS: Mention the new support.
```

**Pull request closed without merging**
