### PR TITLE
Add in support for mips, mipsel + doctests

### PR DESCRIPTION
**Pull request by eQu1NoX**

### CODE REVIEW

**Comment by zachriggle** [comment]
You'll want to rebase this (again, sorry) since it included some broken tests from a commit I made.

**Comment by zachriggle** [comment]
So I pulled this in manually to check it out: https://github.com/binjitsu/binjitsu/tree/eQu1NoX-master

It looks like the usage of `rf` breaks a lot of things in `ROP`: https://travis-ci.org/binjitsu/binjitsu/builds/67122288

I'm really not a fan of this way of doing it, particularly with `condition` and `getstr`.  It's all pretty hacky.  In particular the ARM `offsets` and MIPS `nopadding`/`condition` seem like bandaids that work, but aren't the best way for this to work out.  The functions `fix_offsets` and `_fixup` also need to go, as they're band-aids.

The reason for `offsets` on ARM is that there are fields which have not been assigned names yet.  A unified approach really is necessary.  Either all of the fields must be assigned names (get rid of `offsets`) or all of the fields must use offsets.

Using offsets for *all* fields also fixes the problem that `nopadding` attempts to address, which is that the actual offset of the 4-byte field changes depending on endianness.  By having a completely separate `dict` of `{reg: offset}` or `{offset: reg}` for each `(arch, endian)` pair, this problem goes away.

The new code would look something like this:

```py
# {offset:reg}, though {reg:offset} would work as well
i386 = {0: 'gs', 4: 'fs', ...}
amd64 = {0: 'uc_flags', 8, '&uc', ...}
arm = {0: 'uc_flags', 4: 'uc_link', ..., 'CRUNCH': 232+0xa8}
mips = {0: 'sf_ass0', 4: 'sf_ass1}

# Fix MIPSEL
mipsel = dict(mips)
for field in  ['sc_regmask', 'sc_status']:
    mipsel.pop(field)
for field in mipsel:
    if field > mips['sc_regmask']:
        mipsel[field-8] = mipsel.pop(field)

arches = {
('i386', 'little'): i386,
('i386', 'little'): i386,
('i386', 'little'): i386,
```

**Comment by eQu1NoX** [comment]
`offsets` is not used because the names have not been assigned yet.
http://lxr.free-electrons.com/source/arch/arm/kernel/signal.c#L172 shows how the crunch/iwmmxt/vfp is used. If crunch is present, iwmmxt's offset changes accordingly. if crunch and iwmmxt are present vfp's offset changes accordingly. if only iwmmxt is present vfp's offset changes; if no crunch and iwmmxt were present vfp would be where crunch might have been and so on.
http://lxr.free-electrons.com/source/arch/arm/include/asm/ucontext.h#L86

**Comment by eQu1NoX** [comment]
Anyhow lets make this cleaner. We'd have to keep the following in mind while doing it.
1. coprocessors defined in `offsets` serve the purpose of being able to have values [a, b, c] from a certain base such that if `a` is required, a is at the base. if `a` is not required but `c` is; `c` would be at the base.
2. In Mips regs like pc need a 4 byte padding `after` the big endian packed value. In Mipsel regs like pc need a 4 byte padding `before` the little endian packed value.
3. In Mips there are 2 fields that will not be required in Mipsel, prior to pc.
4. Certain values in mips and mipsel require padding while others don't.

I think that's pretty much it.

**Comment by zachriggle** [comment]
> names have not been assigned yet

I'm not sure what you mean.  All of those structures *have* fields.  They exist, and they're all defined in the same file.

From looking at the config vars, it looks like the only one that will ever matter is CONFIG_VFP.  Let's completely ignore all of the other ones, so that we know the exact names of the fields, and their exact offsets.

- `CONFIG_IWMMXT` will only be enabled on a very few Intel XScale CPUs, which I don't expect to ever turn up (https://en.wikipedia.org/wiki/MMX_(instruction_set)#MMX_in_embedded_applications)
- `CONFIG_CRUNCH` is support for MaverickCrunch on really old Cirrus chips (https://en.wikipedia.org/wiki/MaverickCrunch)
- `CONFIG_VRP` is hardware floating point, like found on Raspberry Pi and newer ARM devices

**Comment by zachriggle** [comment]
> In Mips regs like pc need a 4 byte padding after the big endian packed value. In Mipsel regs like pc need a 4 byte padding before the little endian packed value

If everything is an offset, then everything else is padding.  You don't have to worry about "before" or "after" because the offset will change according to endianness.

**Comment by zachriggle** [comment]
> 3. In Mips there are 2 fields that will not be required in Mipsel, prior to pc.

See my example which handles this

**Comment by zachriggle** [comment]
> 4. Certain values in mips and mipsel require padding while others don't.

If we just use offsets, the entire padding problem goes away

**Comment by eQu1NoX** [comment]
The structure is defined as follows in the link below. Please look at.
http://lxr.free-electrons.com/source/arch/arm/include/asm/ucontext.h#L86

From what I understand, the fields are not present unless the macro is defined. And the macros is not defined unless the proc has that particular coprocessor. As a result, the offsets will vary. Even if we only care about only VFPU, the offsets will be at a varying offset from 232.

**Comment by zachriggle** [comment]
I see the struct.  Assume CONFIG_CRUNCH and CONFIG_IWMMXT will never be enabled, and CONFIG_VPF is always enabled.

The struct will never change, the offsets are known and constant.

**Comment by zachriggle** [comment]
See my earlier comment: https://github.com/binjitsu/binjitsu/pull/31#issuecomment-112733819

**Comment by zachriggle** [comment]
Looks like CI is failing on this

**Comment by zachriggle** [comment]
Ah I'll have to update the ROP side, but the offset dict is good! Because it means now for the ARM VFPU stuff, the ROP.dump() can annotate all the fields, even the ones with offsets :D

**Comment by zachriggle** [comment]
Ping :)

**Comment by eQu1NoX** [comment]
Hi, I've made the commit that uses offset: reg, corrected doctests and rop.py wherever necessary.

**Pull request closed without merging**
